name: Mirroring

on:
  push:
  schedule:
    - cron: '0 15 * * *'
  workflow_dispatch:

jobs:
  to_gitlab:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v2
        with:
          repository: ietf-tools/relaton-data-ieee
          path: relaton-data-ieee
      - name: Copy files
        run: |
          rm -rf data
          cp -r relaton-data-ieee/data ./
      - name: Commit & push changes
        run: |
          echo `date` > flag.txt
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add data flag.txt
          git diff --quiet && git diff --staged --quiet || (git commit -m 'update documents' && git push)