name: Mirroring

on:
  push:
  schedule:
    - cron: '0 15 * * *'
  workflow_dispatch:

jobs:
  to_gitlab:
    runs-on: ubuntu-latest
    steps:
      - uses: wei/git-sync@v3
        with:
          source_repo: "ietf-tools/relaton-data-ieee"
          source_branch: "main"
          destination_repo: "relaton/relaton-data-ieee"
          destination_branch: "main"