name: Mirroring

on:
  push:
  schedule:
    - cron: '0 15 * * *'
  workflow_dispatch:

jobs:
  to_gitlab:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: pixta-dev/repository-mirroring-action@v1
        with:
          target_repo_url:
            git@github.com:ietf-tools/relaton-data-ieee.git